"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
from pathlib import Path
from datetime import timedelta

# Detección temprana de entorno de pruebas para modular arquitectura de base de datos
IS_TESTING = 'test' in sys.argv or 'pytest' in sys.argv or 'pytest' in sys.modules

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-s8-btmb!jw-%t5=z*age7jd1!+m)0$1@kdb8zk*#4f3*$ifc-t')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rrhh',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

# Configuración de Capas para WebSockets con Redis
if 'pytest' in sys.modules:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [(os.environ.get('REDIS_HOST', 'redis'), int(os.environ.get('REDIS_PORT', '6379')))],
            },
        },
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import sys
if 'pytest' in sys.modules or os.environ.get('USE_SQLITE', 'False') == 'True':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'nominarrhh_db'),
            'USER': os.environ.get('POSTGRES_USER', 'admin'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'secretpassword'),
            # IMPORTANTE: Aquí NO va 'localhost'. 
            # como estamos en Docker, el Host es el nombre del servicio de la BD ("db")
            'HOST': os.environ.get('DB_HOST', 'db'),
            'PORT': os.environ.get('DB_PORT', '5432'), 
            'OPTIONS': {
                'options': '-c search_path=django,rrhh,auth,public'
            },
        }
    }

# --- CONFIGURACIÓN DE MULTI-ESQUEMA ---
# Estos routers aseguran que Django use 'django' para sus tablas internas,
# 'auth' para la autenticación de SimpleJWT y 'public' para tu lógica de rrhh.
DATABASE_ROUTERS = [
    'core.db_routers.DjangoSchemaRouter',
    'core.db_routers.AuthSchemaRouter',
]


# Configuración Maestra de Caché apuntando al nuevo servicio Redis
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        # Igual que arriba, el Host maestro es "redis" dentro de la red Docker
        'LOCATION': f"redis://{os.environ.get('REDIS_HOST', 'redis')}:{os.environ.get('REDIS_PORT', '6379')}/1",
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración Maestra: Usamos el sistema de usuarios Legacy de Supabase
AUTH_USER_MODEL = 'rrhh.CustomUser'

# --- Autenticación Estilo Supabase (SimpleJWT con Cookies) ---
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_TOKEN_MINUTES', '15'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_TOKEN_DAYS', '7'))),
    'ROTATE_REFRESH_TOKENS': os.getenv('JWT_ROTATE_REFRESH_TOKENS', 'True') == 'True',
    'BLACKLIST_AFTER_ROTATION': os.getenv('JWT_BLACKLIST_AFTER_ROTATION', 'True') == 'True',
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    
    # Configuración de Cookies (Seguridad Máxima)
    'AUTH_COOKIE': 'access_token',      # Nombre de la cookie para el token de acceso
    'AUTH_COOKIE_REFRESH': 'refresh_token', # Nombre para el token de refresco
    'AUTH_COOKIE_SECURE': not DEBUG,    # Solo se envía por HTTPS en producción
    'AUTH_COOKIE_HTTP_ONLY': True,      # Protege contra XSS (JS no puede leer el token)
    'AUTH_COOKIE_PATH': '/',            # Disponible en todo el sitio
    # SameSite=None necesario cuando frontend y backend están en puertos distintos (cross-origin)
    # En producción (HTTPS) esto es seguro. En dev (HTTP) el browser puede bloquearlo.
    'AUTH_COOKIE_SAMESITE': 'None' if not DEBUG else 'Lax',
    
    # Validación de Integridad
    'ISSUER': os.getenv('JWT_ISSUER', 'NominaRRHH-Backend'),
    'AUDIENCE': os.getenv('JWT_AUDIENCE', 'NominaRRHH-Frontend'),
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rrhh.cookie_auth.CookieJWTAuthentication',  # Lee el token desde Cookie HttpOnly
    )
}

# --- SEGURIDAD AVANZADA (HTTPS / HSTS) ---
if not DEBUG:
    # 1. Forzar HTTPS en todo el backend
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # 2. Cookies Seguras a nivel de Django (Session/CSRF)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # 3. Políticas de Navegador (HSTS)
    SECURE_HSTS_SECONDS = 31536000 # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # 4. Otros Filtros de seguridad
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# --- CONFIGURACIÓN CORS ---
# Nota: NO usar CORS_ALLOW_ALL_ORIGINS=True si se usan Cookies (CORS_ALLOW_CREDENTIALS)
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000').split(',')]

# ESENCIAL: Permite que el navegador envíe Cookies (Tokens) en peticiones Cross-Origin
CORS_ALLOW_CREDENTIALS = True

# --- CONFIGURACIÓN CELERY (REDIS) ---
CELERY_BROKER_URL = f"redis://{os.environ.get('REDIS_HOST', 'redis')}:{os.environ.get('REDIS_PORT', '6379')}/1"
CELERY_RESULT_BACKEND = f"redis://{os.environ.get('REDIS_HOST', 'redis')}:{os.environ.get('REDIS_PORT', '6379')}/1"
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'limpiar-tokens-expirados-diario': {
        'task': 'rrhh.tasks.limpiar_tokens_expirados',
        # Ejecutar todos los días a las 3:00 AM
        'schedule': crontab(hour=3, minute=0),
    },
}
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
