# Generated by Django 5.2.12 on 2026-03-28 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(db_column='encrypted_password', max_length=255)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_sign_in_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('instance_id', models.UUIDField(blank=True, null=True)),
                ('aud', models.CharField(default='authenticated', max_length=255)),
                ('role', models.CharField(default='authenticated', max_length=255)),
                ('is_super_admin', models.BooleanField(db_column='is_super_admin', default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('email_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_token', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_token', models.CharField(blank=True, max_length=255, null=True)),
                ('recovery_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_change_token_new', models.CharField(blank=True, max_length=255, null=True)),
                ('email_change_token_current', models.CharField(blank=True, max_length=255, null=True)),
                ('email_change', models.CharField(blank=True, max_length=255, null=True)),
                ('email_change_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_change_confirm_status', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('phone_change', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_change_token', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_change_sent_at', models.DateTimeField(blank=True, null=True)),
                ('raw_app_meta_data', models.JSONField(blank=True, default=dict, null=True)),
                ('raw_user_meta_data', models.JSONField(blank=True, default=dict, null=True)),
                ('banned_until', models.DateTimeField(blank=True, null=True)),
                ('reauthentication_token', models.CharField(blank=True, max_length=255, null=True)),
                ('reauthentication_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sso_user', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuario Purificado Swissport',
                'db_table': 'users',
                'managed': getattr(settings, 'IS_TESTING', False),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Departamento')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=150, null=True)),
                ('employee_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Cargo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_roles_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_roles_deleted', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='rrhh.department', verbose_name='Departamento')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_roles_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['name'],
                'unique_together': {('name', 'department', 'deleted_at')},
            },
        ),
    ]
