# Generated by Django 5.2.12 on 2026-03-27 02:29

import uuid
import sys
from django.db import migrations, models


def create_auth_schema(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('CREATE SCHEMA IF NOT EXISTS auth;')

def reverse_auth_schema(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('DROP SCHEMA IF EXISTS auth CASCADE;')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_auth_schema, reverse_auth_schema),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=255, db_column='encrypted_password')),
                ('last_login', models.DateTimeField(blank=True, db_column='last_sign_in_at', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
                ('instance_id', models.UUIDField(null=True, blank=True)),
                ('aud', models.CharField(max_length=255, default='authenticated')),
                ('role', models.CharField(max_length=255, default='authenticated')),
                ('raw_user_meta_data', models.JSONField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario de Swissport (Auth)',
                'verbose_name_plural': 'Usuarios de Swissport (Auth)',
                'db_table': 'users' if 'pytest' in sys.modules else 'auth"."users',
            },
        ),
    ]
